apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: watsonx-e2e # Overwritten by template

resources:
- ../vllm/models/mpt-7b-instruct2 # Overwritten by template

patches:
- path: patch-servingruntime.yaml
  target:
    kind: ServingRuntime
  options:
    allowNameChange: true
- path: patch-inferenceservice.yaml
  target:
    kind: InferenceService
  options:
    allowNameChange: true
