apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: isvc
spec:
  predictor:
    model:
      storageUri: s3://psap-hf-models/Llama-2-70b-chat-hf/Llama-2-70b-chat-hf
      args:
        - --dtype=float16
        - --tensor-parallel-size=8
        - --max-model-len=4096
      resources:
        requests:
          cpu: "8"
          memory: "40Gi"
          nvidia.com/gpu: "8"
        limits:
          nvidia.com/gpu: "8"
